### ISSUE TITLE
Does not appear to work

### ISSUE THREAD

**Issue by jwilleke** [GustavoASC/google-drive-vscode#4] opened 2020-09-26 11:06 UTC
Using MACos Latest version of vscode.

Unable to open '2019-02-23-Meeting with the President.gdoc': Unable to read file '/Volumes/GoogleDrive/My Drive/mydata/The Fairways/jims-Community-Fairways/2019-02-23-Meeting with the President.gdoc' (Unknown (FileSystemError): Error: ENOTSUP: operation not supported on socket, open '/Volumes/GoogleDrive/My Drive/mydata/The Fairways/jims-Community-Fairways/2019-02-23-Meeting with the President.gdoc').

**Comment by GustavoASC** [comment] 2020-09-27 20:44
Hello @jwilleke, how are you?
Thanks for opening this issue. :smiley:

Does this problem occur when you try to preview the file, clicking on the preview button like this?

![image](https://user-images.githubusercontent.com/10179520/94375177-31a14f80-00e8-11eb-8a7d-3c9bc5cc1972.png)

Maybe you could record a GIF simulating this problem, so I can see it happening and then have more information about it.
Thanks in advance!

**Comment by GustavoASC** [comment] 2021-02-24 22:57
Hello my friend,

I appreciate you installed the extension!
Unfortunately I couldn't reproduce the problem, so I am closing this issue.

Please feel free to open new issues in case you face the same situation again or face different situations.

**Closed by GustavoASC** 2021-02-24 22:57 UTC
